const providers = [
  {
    uuid: "d5d8eafe-0ee5-4d45-ad4d-1cd25f6f3dfc",
    merchantUuid: "86427179-0ee2-88bc-5456-1c6c45693499",
    dealUuids: ["3f0d9969-2fed-46f0-9257-8ba64b659965"],
    locationUuids: [],
    firstName: "Namefour",
    middleName: "N",
    lastName: "Lastnamefour",
    title: "Registered Nurse",
    abbreviatedTitle: "RN",
    photoUrl: "",
    services: "Injectables",
    boardCertified: false,
    leadProvider: false,
    speciality: "",
    attributes: {
      laserHairRemovalCertification: "",
      injectableCertification: "Some Certification, Some other certification",
      professionalMembership: "AOA",
      fatReductionCertification: ""
    },
    education: "XYZ School of Nursing, Internships at reputed medical hospitals and med-spas",
    aboutMe: "I am a compassionate and competent registered nurse practitioner",
    yearsExperience: 25,
    proceduresPerformed: 1500
  },
  {
    uuid: "f98378bb-8025-46b5-a4d1-5facdd9a908d",
    merchantUuid: "86427179-0ee2-88bc-5456-1c6c45693499",
    dealUuids: ["3f0d9969-2fed-46f0-9257-8ba64b659965"],
    locationUuids: [],
    firstName: "Namefive",
    middleName: "N",
    lastName: "Lastnamefive",
    title: "Registered Nurse",
    abbreviatedTitle: "RN",
    photoUrl: "",
    services: "Injectables",
    boardCertified: false,
    leadProvider: false,
    speciality: "",
    attributes: {
      laserHairRemovalCertification: "",
      injectableCertification: "Some Certification, Some other certification",
      professionalMembership: "AOA",
      fatReductionCertification: ""
    },
    education: "XYZ School of Nursing, Internships at reputed medical hospitals and med-spas",
    aboutMe: "I am a compassionate and competent registered nurse practitioner",
    yearsExperience: 25,
    proceduresPerformed: 1500
  },
  {
    uuid: "8a1a6509-c5a7-489f-8d2f-a13b479d97df",
    merchantUuid: "86427179-0ee2-88bc-5456-1c6c45693499",
    dealUuids: ["3f0d9969-2fed-46f0-9257-8ba64b659965"],
    locationUuids: [],
    firstName: "Nametwo",
    middleName: "N",
    lastName: "Lastnametwo",
    title: "Doctor",
    abbreviatedTitle: "MD",
    photoUrl: "https://img.grouponcdn.com/hbw-signature/LAkZu8DNaRBQ699tN97Rq8qtt2o/10YvK3IRqXnSDYbg8GpoQxJwwpVjOroBB-300x431",
    services: "Injectables",
    boardCertified: true,
    leadProvider: true,
    speciality: "Family Medicine, Emergency Medicine",
    attributes: {
      laserHairRemovalCertification: "",
      injectableCertification: "Botox, Juveau, Xeomin and Dysport certified. Juvederm, Resylane, Radiesse certified. Kybella certified",
      professionalMembership: "AMA, AOA, FAACS",
      fatReductionCertification: ""
    },
    education: "XYZ Medical School, Internships at variaous med spas",
    aboutMe: "I am a qualified doctor with over 30 years of experience. I believe in transparency with my patients and am always available for questions.",
    yearsExperience: 30,
    proceduresPerformed: 2000
  },
  {
    uuid: "c19a4ae5-be44-4492-972a-bfc3e1416a7b",
    merchantUuid: "86427179-0ee2-88bc-5456-1c6c45693499",
    dealUuids: ["3f0d9969-2fed-46f0-9257-8ba64b659965"],
    locationUuids: [],
    firstName: "Namesix",
    middleName: "N",
    lastName: "Lastnamesix",
    title: "Registered Nurse",
    abbreviatedTitle: "RN",
    photoUrl: "",
    services: "Injectables",
    boardCertified: false,
    leadProvider: false,
    speciality: "",
    attributes: {
      laserHairRemovalCertification: "",
      injectableCertification: "Some Certification, Some other certification",
      professionalMembership: "AOA",
      fatReductionCertification: ""
    },
    education: "XYZ School of Nursing, Internships at reputed medical hospitals and med-spas",
    aboutMe: "I am a compassionate and competent registered nurse practitioner",
    yearsExperience: 25,
    proceduresPerformed: 1500
  },
  {
    uuid: "960cb545-ffbd-473e-a2cd-b6608596bdc3",
    merchantUuid: "86427179-0ee2-88bc-5456-1c6c45693499",
    dealUuids: ["3f0d9969-2fed-46f0-9257-8ba64b659965"],
    locationUuids: [],
    firstName: "Nameseven",
    middleName: "N",
    lastName: "Lastnameseven",
    title: "Registered Nurse",
    abbreviatedTitle: "RN",
    photoUrl: "",
    services: "Injectables",
    boardCertified: true,
    leadProvider: true,
    speciality: "",
    attributes: {
      laserHairRemovalCertification: "",
      injectableCertification: "Some Certification, Some other certification",
      professionalMembership: "AOA",
      fatReductionCertification: ""
    },
    education: "XYZ School of Nursing, Internships at reputed medical hospitals and med-spas",
    aboutMe: "I am a compassionate and competent registered nurse practitioner",
    yearsExperience: 25,
    proceduresPerformed: 1500
  },
  {
    uuid: "b6156503-51a5-44e5-bd92-1deb09219b8d",
    merchantUuid: "86427179-0ee2-88bc-5456-1c6c45693499",
    dealUuids: ["3f0d9969-2fed-46f0-9257-8ba64b659965"],
    locationUuids: [],
    firstName: "Namethree",
    middleName: "N",
    lastName: "Lastnamethree",
    title: "Registered Nurse",
    abbreviatedTitle: "RN",
    photoUrl: "https://img.grouponcdn.com/hbw-signature/LAkZu8DNaRBQ699tN97Rq8qtt2o/10YvK3IRqXnSDYbg8GpoQxJwwpVjOroBB-300x431",
    services: "Injectables",
    boardCertified: false,
    leadProvider: false,
    speciality: "",
    attributes: {
      laserHairRemovalCertification: "",
      injectableCertification: "Some Certification, Some other certification",
      professionalMembership: "AOA",
      fatReductionCertification: ""
    },
    education: "XYZ School of Nursing, Internships at reputed medical hospitals and med-spas",
    aboutMe: "I am a compassionate and competent registered nurse practitioner",
    yearsExperience: 25,
    proceduresPerformed: 1500
  }
];

module.exports = providers;